name: Publish docker image

on:
  workflow_dispatch

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Build and publish Docker image
        run: |
          docker build . --tag ghcr.io/pkkht/robotrestapp:latest
          docker push ghcr.io/pkkht/robotrestapp:latest